import React, { useState } from 'react';

// Types matching backend response
interface AnalysisResponse {
    claim_text: string;
    elements: string[];
    prior_art_analyses: PatentAnalysis[];
    overall_risk: {
        novelty_risk: string;
        obviousness_risk: string;
    };
}

interface PatentAnalysis {
    prior_art_id: string;
    title?: string;
    element_analysis: ElementAnalysis[];
    overall_assessment: {
        novelty_risk: string;
        obviousness_risk: string;
        summary: string;
    };
}

interface ElementAnalysis {
    element: string;
    matched_paragraph_ids: string[];
    support_type: string;
    explanation: string;
}

interface AnalysisResultProps {
    data: AnalysisResponse;
}

const RiskBadge: React.FC<{ level: string; label: string }> = ({ level, label }) => {
    const getColor = (l: string) => {
        switch (l.toLowerCase()) {
            case 'high': return 'text-red-400 border-red-500/30 bg-red-500/10';
            case 'medium': return 'text-amber-400 border-amber-500/30 bg-amber-500/10';
            case 'low': return 'text-emerald-400 border-emerald-500/30 bg-emerald-500/10';
            default: return 'text-slate-400 border-slate-500/30 bg-slate-500/10';
        }
    };

    return (
        <div className={`px-4 py-2 rounded-lg border ${getColor(level)} flex items-center gap-2`}>
            <span className="text-xs uppercase tracking-wider font-bold opacity-70">{label}</span>
            <span className="font-bold uppercase">{level}</span>
        </div>
    );
};

const AnalysisResult: React.FC<AnalysisResultProps> = ({ data }) => {
    const [expandedPatent, setExpandedPatent] = useState<string | null>(null);

    const togglePatent = (id: string) => {
        setExpandedPatent(expandedPatent === id ? null : id);
    };

    return (
        <div className="w-full max-w-6xl mx-auto animate-fade-in space-y-8 pb-20">

            {/* Header / Overall Risk */}
            <div className="glass-panel rounded-2xl p-8 flex flex-col md:flex-row justify-between items-start md:items-center gap-6">
                <div>
                    <h2 className="text-3xl font-bold bg-clip-text text-transparent bg-gradient-to-r from-white to-slate-400">
                        Analysis Report
                    </h2>
                    <p className="text-slate-400 mt-2 text-sm">Generated by APEX AI • Strict Citation Mode</p>
                </div>
                <div className="flex gap-4">
                    <RiskBadge level={data.overall_risk.novelty_risk} label="Novelty Risk" />
                    <RiskBadge level={data.overall_risk.obviousness_risk} label="Obviousness Risk" />
                </div>
            </div>

            {/* Prior Art Matches */}
            <div className="space-y-6">
                <h3 className="text-xl font-semibold text-slate-200 pl-2 border-l-4 border-violet-500">
                    Prior Art Evidence
                </h3>

                {data.prior_art_analyses.length === 0 ? (
                    <div className="glass-panel rounded-xl p-8 text-center border border-dashed border-slate-600">
                        <div className="text-4xl mb-4">🤷‍♂️</div>
                        <h4 className="text-xl font-bold text-white mb-2">No Relevant Prior Art Found</h4>
                        <p className="text-slate-400 max-w-lg mx-auto">
                            We searched our database but couldn't find any patents sufficiently similar to your claim.
                            This suggests your invention might be highly novel (or our database is too small).
                        </p>
                        <div className="mt-6 inline-block px-4 py-2 rounded bg-emerald-500/10 border border-emerald-500/30 text-emerald-400 text-sm font-bold">
                            Result: Low Risk (Novel)
                        </div>
                    </div>
                ) : (
                    data.prior_art_analyses.map((patent) => (
                        <div key={patent.prior_art_id} className="glass-panel rounded-xl overflow-hidden transition-all duration-300">
                            {/* Patent Header */}
                            <div
                                className="p-6 cursor-pointer hover:bg-white/5 flex justify-between items-center"
                                onClick={() => togglePatent(patent.prior_art_id)}
                            >
                                <div className="flex items-center gap-4">
                                    <div className="h-12 w-12 rounded-full bg-violet-500/20 flex items-center justify-center text-violet-400 font-bold text-lg">
                                        US
                                    </div>
                                    <div>
                                        <h4 className="text-lg font-bold text-white">{patent.prior_art_id}</h4>
                                        <p className="text-slate-400 text-sm">{patent.title || "Patent Title Unavailable"}</p>
                                    </div>
                                </div>
                                <div className="flex items-center gap-6">
                                    <div className="text-right hidden md:block">
                                        <div className="text-xs text-slate-500 uppercase">Novelty</div>
                                        <div className={`font-bold ${patent.overall_assessment.novelty_risk.toLowerCase() === 'high' ? 'text-red-400' : 'text-emerald-400'}`}>
                                            {patent.overall_assessment.novelty_risk}
                                        </div>
                                    </div>
                                    <svg
                                        className={`w-6 h-6 text-slate-500 transform transition-transform ${expandedPatent === patent.prior_art_id ? 'rotate-180' : ''}`}
                                        fill="none" viewBox="0 0 24 24" stroke="currentColor"
                                    >
                                        <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M19 9l-7 7-7-7" />
                                    </svg>
                                </div>
                            </div>

                            {/* Expanded Content */}
                            {expandedPatent === patent.prior_art_id && (
                                <div className="p-6 border-t border-white/5 bg-black/20">
                                    <p className="text-slate-300 mb-8 italic border-l-2 border-slate-600 pl-4 py-2">
                                        "{patent.overall_assessment.summary}"
                                    </p>

                                    <div className="space-y-4">
                                        {patent.element_analysis.map((elem, idx) => (
                                            <div key={idx} className="glass-card rounded-lg p-5">
                                                <div className="flex justify-between items-start mb-3">
                                                    <h5 className="font-medium text-white w-3/4">
                                                        <span className="text-violet-400 mr-2">{idx + 1}.</span>
                                                        {elem.element}
                                                    </h5>
                                                    <span className={`text-xs px-2 py-1 rounded border ${elem.support_type === 'anticipated' ? 'border-red-500/50 text-red-400 bg-red-500/10' :
                                                            elem.support_type === 'obvious' ? 'border-amber-500/50 text-amber-400 bg-amber-500/10' :
                                                                'border-emerald-500/50 text-emerald-400 bg-emerald-500/10'
                                                        }`}>
                                                        {elem.support_type.toUpperCase()}
                                                    </span>
                                                </div>

                                                <p className="text-slate-400 text-sm leading-relaxed mb-3">
                                                    {elem.explanation}
                                                </p>

                                                {elem.matched_paragraph_ids.length > 0 && (
                                                    <div className="flex gap-2 flex-wrap">
                                                        {elem.matched_paragraph_ids.map(pid => (
                                                            <span key={pid} className="text-xs bg-violet-500/20 text-violet-300 px-2 py-1 rounded hover:bg-violet-500/30 cursor-pointer transition-colors">
                                                                ¶ {pid}
                                                            </span>
                                                        ))}
                                                    </div>
                                                )}
                                            </div>
                                        ))}
                                    </div>
                                </div>
                            )}
                        </div>
                    ))
                )}
            </div>
        </div>
    );
};

export default AnalysisResult;
